export const authType = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const projectType = {
  CREATE_PROJECT_REQUEST: "CREATE_PROJECT_REQUEST",
  CREATE_PROJECT_SUCCESS: "CREATE_PROJECT_SUCCESS",
  CREATE_PROJECT_FAILURE: "CREATE_PROJECT_FAILURE",

  GET_ALLTABLE_REQUEST: "GET_ALLTABLE_REQUEST",
  GET_ALLTABLE_SUCCESS: "GET_ALLTABLE_SUCCESS",
  GET_ALLTABLE_FAILURE: "GET_ALLTABLE_FAILURE",

  GET_ALL_ELEMENT_LABELX_REQUEST: "GET_ALL_ELEMENT_LABELX_REQUEST",
  GET_ALL_ELEMENT_LABELX_SUCCESS: " GET_ALL_ELEMENT_LABELX_SUCCESS",
  GET_ALL_ELEMENT_LABELX_FAILURE: "GET_ALL_ELEMENT_LABELX_FAILURE",
};

export const chartType = {
  CREATE_PROJECT_CHART_REQUEST: "CREATE_PROJECT_CHART_REQUEST",
  CREATE_PROJECT_CHART_SUCCESS: "CREATE_PROJECT_CHART_SUCCESS",
  CREATE_PROJECT_CHART_FAILURE: "CREATE_PROJECT_CHART_FAILURE",

  GET_ALLCHART_REQUEST: "GET_ALLCHART_REQUEST",
  GET_ALLCHART_SUCCESS: "GET_ALLCHART_SUCCESS",
  GET_ALLCHART_FAILURE: "GET_ALLCHART_FAILURE",

  GET_PROJECT_PAGE_REQUEST: "GET_PROJECT_PAGE_REQUEST",
  GET_PROJECT_PAGE_SUCCESS: "GET_PROJECT_PAGE_SUCCESS",
  GET_PROJECT_PAGE_FAILURE: "GET_PROJECT_PAGE_FAILURE",

  GET_ELEMENT_BY_LABELX_REQUEST: "GET_ELEMENT_BY_LABELX_REQUEST",
  GET_ELEMENT_BY_LABELX_SUCCESS: "GET_ELEMENT_BY_LABELX_SUCCESS",
  GET_ELEMENT_BY_LABELX_FAILURE: "GET_ELEMENT_BY_LABELX_FAILURE",

  CLEAR_CHART: "CLEAR_CHART",

  GET_QUERY_DATA_CHART_GROUP_X_Y_REQUEST:
    "GET_QUERY_DATA_CHART_GROUP_X_Y_REQUEST",
  GET_QUERY_DATA_CHART_GROUP_X_Y_SUCCESS:
    "GET_QUERY_DATA_CHART_GROUP_X_Y_SUCCESS",
  GET_QUERY_DATA_CHART_GROUP_X_Y_FAILURE:
    "GET_QUERY_DATA_CHART_GROUP_X_Y_FAILURE",
};

export const dashboardType = {
  CREATE_PROJECT_DASHBOARD_REQUEST: "CREATE_PROJECT_DASHBOARD_REQUEST",
  CREATE_PROJECT_DASHBOARD_SUCCESS: "CREATE_PROJECT_DASHBOARD_SUCCESS",
  CREATE_PROJECT_DASHBOARD_FAILURE: "CREATE_PROJECT_DASHBOARD_FAILURE",

  GET_ALL_CHART_REQUEST: "GET_ALL_CHART_REQUEST",
  GET_ALL_CHART_SUCCESS: "GET_ALL_CHART_SUCCESS",
  GET_ALL_CHART_FAILURE: "GET_ALL_CHART_FAILURE",

  GET_CHART1_SUCCESS: "GET_CHART1_SUCCESS",
  GET_CHART2_SUCCESS: "GET_CHART2_SUCCESS",
  GET_CHART3_SUCCESS: "GET_CHART3_SUCCESS",
  GET_CHART4_SUCCESS: "GET_CHART4_SUCCESS",

  GET_ALL_DASHBOARD_REQUEST: "GET_ALL_DASHBOARD_REQUEST",
  GET_ALL_DASHBOARD_SUCCESS: "GET_ALL_DASHBOARD_SUCCESS",
  GET_ALL_DASHBOARD_FAILURE: "GET_ALL_DASHBOARD_FAILURE",

  GET_DASH_BY_SLUG_REQUEST: "GET_DASH_BY_SLUG_REQUEST",
  GET_DASH_BY_SLUG_SUCCESS: "GET_DASH_BY_SLUG_SUCCESS",
  GET_DASH_BY_SLUG_FAILURE: "GET_DASH_BY_SLUG_FAILURE",

  SAVE_STATE_DASHBOARD_REQUEST: "SAVE_STATE_DASHBOARD_REQUEST",
  SAVE_STATE_DASHBOARD_SUCCESS: "SAVE_STATE_DASHBOARD_SUCCESS",
  SAVE_STATE_DASHBOARD_FAILURE: "SAVE_STATE_DASHBOARD_FAILURE",
};
